- alias: "Working from home daytime"
  trigger:
    platform: time
    at: "06:30:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: input_boolean.vacationmode
      state: "off"
  action:
    service: climate.set_temperature
    data:
      temperature: 20
    target:
      entity_id:
        - climate.heater1
        - climate.heater2

- alias: "Night temps during the week"
  trigger:
    platform: time
    at: "22:00:00"
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - sun
    - condition: state
      entity_id: input_boolean.vacationmode
      state: "off"
  action:
    service: climate.set_temperature
    data:
      temperature: 15
    target:
      entity_id:
        - climate.heater1
        - climate.heater2

- alias: "Daytime weekend"
  trigger:
    platform: time
    at: "07:30:00"
  condition:
    - condition: time
      weekday:
        - sat
        - sun
    - condition: state
      entity_id: input_boolean.vacationmode
      state: "off"
  action:
    service: climate.set_temperature
    data:
      temperature: 20
    target:
      entity_id:
        - climate.heater1
        - climate.heater2

- alias: "Night temps during weekend"
  trigger:
    platform: time
    at: "23:30:00"
  condition:
    - condition: time
      weekday:
        - fri
        - sat
    - condition: state
      entity_id: input_boolean.vacationmode
      state: "off"
  action:
    service: climate.set_temperature
    data:
      temperature: 15
    target:
      entity_id:
        - climate.heater1
        - climate.heater2

- alias: "Vacation mode on"
  trigger:
    platform: state
    entity_id: input_boolean.vacationmode
    to: "on"
  action:
    service: climate.set_temperature
    data:
      temperature: 12
    target:
      entity_id:
        - climate.heater1
        - climate.heater2

- alias: "Vacation mode off"
  trigger:
    platform: state
    entity_id: input_boolean.vacationmode
    to: "off"
  action:
    service: climate.set_temperature
    data:
      temperature: 20
    target:
      entity_id:
        - climate.heater1
        - climate.heater2
